name: Generate Pacman Graph

on:
  schedule: # Run every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main
permissions:
  contents: write 
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Generate Pacman contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          # The output branch where the SVG will be pushed
          # Make sure to create this branch or the action will fail
          # If it doesn't exist, the action usually creates it
          output_branch: output
          output_path: pacman-contribution-graph.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
